"""empty message

Revision ID: 4ab1d4a78621
Revises: 9bd061f57a75
Create Date: 2025-05-03 11:43:41.984502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab1d4a78621'
down_revision: Union[str, None] = '9bd061f57a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.String(), nullable=False))
    op.add_column('user_profile', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('user_profile', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('user_profile', sa.Column('username', sa.String(), nullable=False))
    op.add_column('user_profile', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user_profile', ['email'])
    op.create_unique_constraint(None, 'user_profile', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.drop_column('user_profile', 'email')
    op.drop_column('user_profile', 'username')
    op.drop_column('user_profile', 'last_name')
    op.drop_column('user_profile', 'first_name')
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###
